baseURL = "https://omairmajid.com/"
languageCode = "en"
title = "Omair Majid"
theme = "vitae"
copyright = "© Omair Majid 2011 - 2020 | [License](/about/) | [Source](https://github.com/omajid/omajid.github.io/tree/blog)"

[params]
  author = "Omair Majid"
  description = "Omair's announcements, thouughts and code"
  subtitle = "Announcements, thoughts, code and fun"
  avatar = "https://github.com/omajid.png"

  mainSections = ["posts"]

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Talks"
  url = "/talks/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[[params.social]]
  name = "Email"
  icon = "fas fa-envelope"
  url = "mailto:omair.majid@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "fab fa-github"
  url = "https://github.com/omajid"

# [[params.social]]
#   name = "LinkedIn"
#   icon = "fab fa-linkedin"
#   url = "/about/"  # FIXME

[[params.social]]
  name = "Reddit"
  icon = "fab fa-reddit"
  url = "https://www.reddit.com/user/omair-majid"

[[params.social]]
  name = "StackOverflow"
  icon = "fab fa-stack-overflow"
  url = "https://stackoverflow.com/story/omajid"

# [[params.social]]
#   name = "Twitter"
#   icon = "fab fa-twitter"
#   url = "/about/"  # FIXME

[[params.social]]
  name = "RSS"
  icon = "fas fa-rss"
  url = "/index.xml"
